FROM busybox:1.37 AS prep
RUN mkdir /data

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=prep --chown=65532:65532 /data /data
COPY relay-linux-amd64 /relay
USER nonroot
ENTRYPOINT ["/relay", "serve", "-addr", ":8460", "-data", "/data"]
