#!/usr/bin/env bash
# Renders the app icon everywhere from its two sources:
#   app/assets/icon/background.svg  foreground.svg   (108×108, Android adaptive layout)
# Writes: app/assets/icon/icon.svg and site/icon.svg (both layers in one),
#   Android mipmaps (adaptive layers, monochrome, legacy) and the macOS AppIcon.
# Needs Google Chrome (headless renders the SVG) and sips (resizes).
# Usage: scripts/icons.sh        (via ./dev.sh icons)
set -euo pipefail
cd "$(dirname "$0")/.."

CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
[ -x "$CHROME" ] || { echo "icons: needs Google Chrome" >&2; exit 1; }
SRC=app/assets/icon
RES=app/android/app/src/main/res
MAC=app/macos/Runner/Assets.xcassets/AppIcon.appiconset
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# One SVG with both layers (favicon, site, anything that wants a file).
inner() { grep -v -e '^<svg' -e '^</svg' -e '^<!--' -e '^     ' "$1"; }
{
  echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108">'
  echo '<!-- Generated by ./dev.sh icons from background.svg + foreground.svg: edit those. -->'
  inner $SRC/background.svg
  inner $SRC/foreground.svg
  echo '</svg>'
} >$SRC/icon.svg
cp $SRC/icon.svg site/icon.svg

# render name size css-for-the-stack layers…: a page with the layers stacked, screenshotted.
render() {
  local name=$1 size=$2 css=$3; shift 3
  local imgs=""
  for l in "$@"; do imgs+="<img src=\"$PWD/$SRC/$l.svg\" class=\"$l\">"; done
  cat >"$TMP/$name.html" <<EOF
<!doctype html><style>
html,body{margin:0;background:transparent}
.s{position:relative;width:${size}px;height:${size}px;overflow:hidden;$css}
img{position:absolute;inset:0;width:100%;height:100%}
.mono{filter:brightness(0) invert(1)}
</style><div class="s">$imgs</div>
EOF
  "$CHROME" --headless --disable-gpu --hide-scrollbars --force-device-scale-factor=1 \
    --default-background-color=00000000 --window-size=$size,$size \
    --screenshot="$TMP/$name.png" "file://$TMP/$name.html" >/dev/null 2>&1
  [ -s "$TMP/$name.png" ] || { echo "icons: render $name failed" >&2; exit 1; }
}

# Masters at 1024, then sips scales them down.
render bg 1024 "" background
render fg 1024 "" foreground
sed 's/class="foreground"/class="foreground mono"/' "$TMP/fg.html" >"$TMP/mono.html"
"$CHROME" --headless --disable-gpu --hide-scrollbars --force-device-scale-factor=1 \
  --default-background-color=00000000 --window-size=1024,1024 \
  --screenshot="$TMP/mono.png" "file://$TMP/mono.html" >/dev/null 2>&1
render legacy 1024 "border-radius:22%" background foreground
# macOS: the Big Sur grid, an 824 rounded square inside 1024 with a soft shadow.
cat >"$TMP/mac.html" <<EOF
<!doctype html><style>
html,body{margin:0;background:transparent}
.s{position:absolute;left:100px;top:92px;width:824px;height:824px;border-radius:185px;overflow:hidden;
  box-shadow:0 10px 24px rgba(0,0,0,.35)}
img{position:absolute;inset:0;width:100%;height:100%}
</style><div class="s"><img src="$PWD/$SRC/background.svg"><img src="$PWD/$SRC/foreground.svg"></div>
EOF
"$CHROME" --headless --disable-gpu --hide-scrollbars --force-device-scale-factor=1 \
  --default-background-color=00000000 --window-size=1024,1024 \
  --screenshot="$TMP/mac.png" "file://$TMP/mac.html" >/dev/null 2>&1

scale() { sips -z "$2" "$2" "$1" --out "$3" >/dev/null; }

# Android: adaptive layers are 108dp, the legacy icon 48dp.
for d in mdpi:1 hdpi:1.5 xhdpi:2 xxhdpi:3 xxxhdpi:4; do
  dir=$RES/mipmap-${d%%:*} f=${d##*:}
  mkdir -p "$dir"
  n=$(awk "BEGIN{print int(108*$f)}") l=$(awk "BEGIN{print int(48*$f)}")
  scale "$TMP/bg.png" "$n" "$dir/ic_launcher_background.png"
  scale "$TMP/fg.png" "$n" "$dir/ic_launcher_foreground.png"
  scale "$TMP/mono.png" "$n" "$dir/ic_launcher_monochrome.png"
  scale "$TMP/legacy.png" "$l" "$dir/ic_launcher.png"
done
cat >$RES/mipmap-anydpi-v26/ic_launcher.xml <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ./dev.sh icons (scripts/icons.sh). -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
EOF
rm -f $RES/drawable/ic_launcher_background.xml $RES/drawable/ic_launcher_foreground.xml

for s in 16 32 64 128 256 512 1024; do scale "$TMP/mac.png" $s "$MAC/app_icon_$s.png"; done
echo "icons: Android mipmaps, macOS AppIcon, icon.svg and site/icon.svg written"
